"""Generate on-device assets for the ESP32 sketch:
  - firmware/esp32_llm/vocab.h : token id -> raw UTF-8 bytes, so the device just
    Serial.write()s the bytes of each generated token (llama2.c style).
  - firmware/esp32_llm/bpe.h   : the ENCODE direction -- byte->token seeds plus
    the merge table, so the device can tokenize text typed over serial instead
    of relying on prompt ids baked in at build time.
  - prints the prompt token ids for a fixed demo prompt to paste into the sketch.
"""

import json
import os

from tokenizers import Tokenizer

HERE = os.path.dirname(os.path.abspath(__file__))
TOK = os.path.join(HERE, "..", "data", "bpe32768.json")
OUT = os.path.join(HERE, "..", "firmware", "esp32_llm", "vocab.h")
BPE_OUT = os.path.join(HERE, "..", "firmware", "esp32_llm", "bpe.h")
PROMPT = "Once upon a time"


def bytes_to_unicode():
    """GPT-2's byte <-> printable-codepoint map, as used by ByteLevel.

    Reproduced here rather than imported because the C encoder needs the exact
    same table baked in; if these two ever disagree the device tokenizes
    differently from training and perplexity silently degrades.
    """
    bs = (list(range(ord("!"), ord("~") + 1))
          + list(range(ord("¡"), ord("¬") + 1))
          + list(range(ord("®"), ord("ÿ") + 1)))
    cs = bs[:]
    n = 0
    for b in range(256):
        if b not in bs:
            bs.append(b)
            cs.append(256 + n)
            n += 1
    return {b: chr(c) for b, c in zip(bs, cs)}


def write_bpe_header(vocab, merges):
    """Emit the merge table sorted by (id_a<<16|id_b) so C can binary-search it.

    Storing rank alongside the merged id is what lets the device run real BPE
    (always apply the lowest-rank adjacent pair) rather than a greedy
    longest-match approximation, which would not match the training tokenizer.
    """
    b2u = bytes_to_unicode()
    byte_tok = []
    for b in range(256):
        ch = b2u[b]
        if ch not in vocab:
            raise SystemExit(f"byte {b} -> {ch!r} missing from vocab")
        byte_tok.append(vocab[ch])

    entries = []
    for rank, pair in enumerate(merges):
        a, b = pair if isinstance(pair, (list, tuple)) else pair.split(" ", 1)
        merged = a + b
        if a not in vocab or b not in vocab or merged not in vocab:
            continue  # merge whose product was pruned from the final vocab
        entries.append(((vocab[a] << 16) | vocab[b], rank, vocab[merged]))
    entries.sort(key=lambda e: e[0])

    def rows(vals, per_line, fmt=str):
        out = []
        for i in range(0, len(vals), per_line):
            out.append("  " + ",".join(fmt(v) for v in vals[i:i + per_line]) + ",")
        return "\n".join(out)

    with open(BPE_OUT, "w") as f:
        f.write("// Generated by src/gen_assets.py -- BPE encode tables.\n")
        f.write("// Sorted by pair key so the device can binary-search merges.\n")
        f.write("// Fixed-width types matter: on Xtensa `uint32_t` is `long unsigned\n")
        f.write("// int`, so plain `unsigned int` arrays fail to bind to the Bpe struct.\n")
        f.write("#ifndef BPE_H\n#define BPE_H\n#include <stdint.h>\n\n")
        f.write(f"#define BPE_N_PAIRS {len(entries)}\n\n")
        f.write("static const uint16_t BPE_BYTE_TOK[256] = {\n")
        f.write(rows(byte_tok, 16))
        f.write("\n};\n\n")
        f.write(f"static const uint32_t BPE_PAIR_KEY[BPE_N_PAIRS] = {{\n")
        f.write(rows([e[0] for e in entries], 10, lambda v: f"{v}u"))
        f.write("\n};\n\n")
        f.write(f"static const uint16_t BPE_PAIR_RANK[BPE_N_PAIRS] = {{\n")
        f.write(rows([e[1] for e in entries], 16))
        f.write("\n};\n\n")
        f.write(f"static const uint16_t BPE_PAIR_NEW[BPE_N_PAIRS] = {{\n")
        f.write(rows([e[2] for e in entries], 16))
        f.write("\n};\n\n#endif\n")

    kb = (len(entries) * 8 + 512) / 1024
    print(f"wrote {BPE_OUT}: {len(entries)} merges, ~{kb:.0f} KB of tables")


def main():
    tok = Tokenizer.from_file(TOK)
    V = tok.get_vocab_size()

    # Raw bytes per token: decode single-id sequences. For the ASCII TinyStories
    # domain this reconstructs text exactly when pieces are concatenated.
    blob = bytearray()
    offs = [0]
    for i in range(V):
        s = tok.decode([i])
        blob.extend(s.encode("utf-8"))
        offs.append(len(blob))

    with open(OUT, "w") as f:
        f.write("// Generated by src/gen_assets.py -- token id -> raw UTF-8 bytes.\n")
        f.write("#ifndef VOCAB_H\n#define VOCAB_H\n")
        f.write(f"#define VOCAB_N {V}\n")
        f.write(f"static const unsigned char VOCAB_BLOB[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 20):
            f.write("  " + ",".join(str(b) for b in blob[i:i+20]) + ",\n")
        f.write("};\n")
        f.write(f"static const int VOCAB_OFF[{len(offs)}] = {{\n")
        for i in range(0, len(offs), 20):
            f.write("  " + ",".join(str(o) for o in offs[i:i+20]) + ",\n")
        f.write("};\n#endif\n")

    print(f"wrote {OUT}: {V} tokens, blob {len(blob)/1024:.0f} KB")

    raw = json.load(open(TOK))
    write_bpe_header(raw["model"]["vocab"], raw["model"]["merges"])

    ids = tok.encode(PROMPT).ids
    print(f'prompt "{PROMPT}" -> {len(ids)} ids: {ids}')
    print(f"round-trip: {tok.decode(ids)!r}")
    print("\nThe sketch tokenizes typed input on-device via bpe.h, so no prompt "
          "ids need pasting.\nCheck the encoder against this tokenizer with:"
          "\n  cc -O3 -o /tmp/tok_test firmware/host_verify/tok_test.c"
          "\n  uv run python src/tok_check.py")


if __name__ == "__main__":
    main()
